# Generated by Django 4.0 on 2021-12-10 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imageUrl',
            new_name='image_url',
        ),
    ]
